version: '3.9'

services:
  webrtc-chat-turn-server:
    image: coturn/coturn:latest
    restart: always
    network_mode: 'host'
    volumes:
      - ./ssl:/etc/letsencrypt/live/webrtc-chat-app-demo.site
    command: -n --log-file=stdout
        --min-port=49160
        --max-port=49200
        --external-ip=${TURN_SERVER_IP}
        --realm=${TURN_SERVER_HOSTNAME}
        --server-name=webrc-chat-turn-server
        --user=${TURN_SERVER_USERNAME}:${TURN_SERVER_PASSWORD}
        --listening-port=${TURN_SERVER_PORT}
        --tls-listening-port=5349
        --cert=/etc/letsencrypt/live/webrtc-chat-app-demo.site/cert.pem
        --pkey=/etc/letsencrypt/live/webrtc-chat-app-demo.site/privkey.pem
        --listening-ip=0.0.0.0
        --fingerprint
        --lt-cred-mech

  webrtc-chat-server:
    restart: on-failure
    args:
      TURN_SERVER_HOSTNAME: ${TURN_SERVER_HOSTNAME}
      TURN_SERVER_PORT: ${TURN_SERVER_PORT}
      TURN_SERVER_USERNAME: ${TURN_SERVER_USERNAME}
      TURN_SERVER_PASSWORD: ${TURN_SERVER_PASSWORD}
    build: .
    depends_on:
      - webrtc-chat-turn-server

  webrtc-chat-nginx:
    image: nginx
    volumes:
      - ./ssl:/etc/letsencrypt/live/webrtc-chat-app-demo.site
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '443:443'
    depends_on:
      - webrtc-chat-server
