name: CI

on:
  workflow_dispatch:

  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  lint:
    name: Run linters
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Run linters
        run: pnpm run turbo lint
